### ISSUE TITLE
Move dark mode OS detection logic to ThemeProvider

### ISSUE THREAD

**Issue by gazpachu** [tablecheck/tablekit#10]
There are already several apps detecting the OS appearance. We should make this more DRY and just have in a single place, like the TableKit ThemeProvider.

**Comment by SimeonC** [comment]
There is already OSS hooks for this like here - https://github.com/rfoel/use-prefers-color-scheme. I'd prefer we just recommend use them and not internalise this.

In the case of dark mode, I think we do need to look at all the components and how theming is done to see if we can simplify the setup of it. A lot of our components just do renaming via the theme so I think it'd be great if we could just remove the whole thing if possible - `alert.something.border => theme.colors.border`
