### ISSUE TITLE
Add `Button Group` Component

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#101]
**Location**: `system/react/src/components/ButtonGroup.ts`
**Exports**: `classySelector = '.button-group'` `ButtonGroup = styled.span`
**Designs**: https://www.figma.com/file/W3hxWj6VZydNaNGJSGxRsV/TableKit-Components-(3.0)?node-id=2259%3A74833
**Other Notes**:
- Needs a storybook - single story inside file with all the variants.
- Should handle all changes via child selectors `& > * {` - use first-child/last-child
- The "selected" state should be applied both `:checked` or `[data-selected="true"]` so this can be used as a "checkbox", "radio" or "button".

@xsanctom to review active, hover and focus states.

**Comment by gazpachu** [comment]
Done and merged
