### ISSUE TITLE
Add ` Icon Button` Component

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#102]
**Location**: `system/react/src/components/IconButton.ts`
**Exports**: `classlessSelector = 'button.icon, a[type="button"].icon'` `classySelector = '.icon-button'` `IconButton`
**Designs**: https://www.figma.com/file/W3hxWj6VZydNaNGJSGxRsV/TableKit-Components-(3.0)?node-id=1881%3A43945
**Other Notes**: Needs a storybook - single story inside file with all the variants.

**Comment by hachi-studio** [comment]
Been a while, need to rebase and remind myself where I left off, will sort out tomorrow 🙇
