### ISSUE TITLE
Add `Chip` Component

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#104]
**Location**: `system/react/src/components/Chip.ts`
**Exports**: `classySelector = '.chip'` `ButtonGroup = styled.span`
**Designs**: https://www.figma.com/file/W3hxWj6VZydNaNGJSGxRsV/TableKit-Components-(3.0)?node-id=1509%3A77739
**Other Notes**: Needs a storybook - single story inside file with all the variants.

**Comment by hachi-studio** [comment]
Been a while, need to rebase and remind myself where I left off, will sort out tomorrow 🙇
