### ISSUE TITLE
Implement Visual Regression Testing. With something like Chromatic?

### ISSUE THREAD

**Issue by gazpachu** [tablecheck/tablekit#11]
As we are mostly concerned with how it looks this is a very good test. We will need to do something unusual for things like modal and tooltip to correctly figure those out.

**Comment by SimeonC** [comment]
I think our stories for modals and tooltips are a bit unusual for stories. Really we shouldn't have a button or trigger for those stories but just show the modal/tooltip automatically. Having both for documentation is fine but there wouldn't be much unusual for the chromatic tests for modals and tooltips other than forcing them open at the start.

**Comment by gazpachu** [comment]
Done in the `next` branch. Closing ticket
