### ISSUE TITLE
Test storybook and the figma plugin

### ISSUE THREAD

**Issue by gazpachu** [tablecheck/tablekit#12]
https://help.figma.com/hc/en-us/articles/360045003494-Storybook-and-Figma

Joan:

Simeon Cheeseman the figma plugin I found for storybook doesn't focus on component uploading to figma. What it does is show the figma component side-by-side with the storybook implementation. Have you found anything else that allows the single source of truth?

Simeon:

Nice, that figma plugin looks neat, definitely great for checking if we match the figma library. There seemed to be Figma → React type plugins out there and [official support](https://www.figma.com/blog/introducing-figma-to-react/)?, but unfortunately, it looks like Figma are insistent on Figma being the single source of truth to the degree that they encrypt their files so you can’t even read them as “source code”. Their API is also read-only (currently). Sketch was better in this sense as a sketch file is just an zip file of xml files so you could programatically work with that.

I think the best we could probably do is a script the other way that listens for changes to the figma library and raises MRs to tablekit repo (they have webhooks). Unless Figma magically support writing to their API anytime soon   

It’d take a fair amount of work, and probably some minor structural/naming changes in tablekit to support auto-update. But I think we could do it, usage of custom jsDoc style comments or something + AST Parsers.

**Comment by SimeonC** [comment]
Originally I thought we were going to do similar to what Lehel used to do with Sketch in Figma, as it seems that they aren't going to catalogue all components in Figma I think this is probably not going to be of any use anymore. Our single source of truth would have to be the code because Figma doesn't cover all the cases.
