### ISSUE TITLE
`MenuItem` conflict with specifity of `Menu` sub selector

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#162]
https://github.com/tablecheck/tablekit/blob/464aefb265eb5b967b4376c5db90b081109be012/system/react/src/components/MenuList.ts#L24-L27

In the above-linked code the specificity of this selector means that the `MenuItem` cannot be overwritten in styles. We need to move this style to the `MenuItem` styles specifically.

**Comment by Maruth51** [comment]
Hi @SimeonC 

I think the has been changed and this issue is not applicable now

[https://github.com/tablecheck/tablekit/blob/next/system/react/src/components/MenuList.tsx](url)
