### ISSUE TITLE
Add stories for InputAlert and InputStructure

### ISSUE THREAD

**Issue by SimeonC** [tablecheck/tablekit#174]

**Comment by Maruth51** [comment]
Hi @SimeonC 

Is anyone working on this? I would like to take this.

**Comment by SimeonC** [comment]
Hi @Maruth51, thanks for all your PRs! Much appreciated, no one is currently working on this so feel free to pick it up.
Just to let you know I'm on leave this week as is most of our dev team who review and work on Tablekit so I'll make sure I figure out what the issue is with the CI on your PRs is on next Monday and we'll get them merged in. It's not something you have to worry about, we just haven't had any external contributions till now so we have some teething problems.
