### ISSUE TITLE
Clarify icon configuration for tablekit usage

### ISSUE THREAD

**Issue by wahidfarid** [tablecheck/tablekit#4]
We should clarify for anyone trying to use tablekit that they probably need to  import an icon configuration for most components to work properly (e.g. `import '@tablecheck/tablekit-free-icon-config';` in the project root)

**Comment by gazpachu** [comment]
@irmir let's migrate the `Iconography` page from http://tablekit.tablecheck.com/#/Icon%20System into Storybook and also add to the page what Wahid mentioned above.

**Comment by irmir** [comment]
@wahidmagdy @gazpachu maybe we need to include this information in every package that needed icon configuration? Also Wahid I would be appreciate if you would name this packages ( I’ll list them in the Iconography. "If you have to use ...... components you need to import an icon configuration in the project root  `import '@tablecheck/tablekit-free-icon-config'; `  - is it ok? )

**Comment by SimeonC** [comment]
With my latest change adding errors details to this everywhere here https://github.com/tablecheck/tablekit/pull/48 we shouldn't need this in every package. I think it should be in `/README.md` as that's what a lot of Dev's will read first as NPM will send you to the README before any of the website. Though the README does need cleanup as all the information there currently should be classified as "Development". For the README can you do the following;
1. Make the main headers (## header) `Getting Started` and `Development`
2. Move the existing `Installation`, `Testing` and the contents of current `Development` into the new `Development` section.
3. In the `Getting Started` section write some text about the website and some absolute minimum examples - theme, icons config etc. (Have a go writing something that makes sense to you, it's document writing so we only learn by practice. I'd think about trying to explain to someone how to add the tablekit button to a brand new react app).

Also as Joan mentioned add a note to the migrated Iconography that we should migrate.
