### ISSUE TITLE
Refactor button and link colors

### ISSUE THREAD

**Issue by gazpachu** [tablecheck/tablekit#66]
Source: https://www.figma.com/file/A9TifYqf6KaiLwgbH4Ns4S/Theming?node-id=85%3A17646

Right now both all links and buttons use the same token, they should be separate. Example: standard buttons should use primary1, and links, icons and outline buttons use primary2

 Hover / active should automatically make it 10% darker  

NOTE: I am aware our current darkmode / classic colors are inverse, this should be a case of just flipping the values on our TC theme.

**Comment by SimeonC** [comment]
I think that buttons and links need a more heavy refactor than just the colour switching. Also of note that the "outline" buttons in figma use primary1 for the text and primary 2 for the border.

**Comment by gazpachu** [comment]
Which figma file are you referring to?

**Comment by SimeonC** [comment]
Ah, you linked the Diner theming, I was referring to the Tablekit one https://www.figma.com/file/PCCFmEYNYBC9EkBDwgqMPw/Components?node-id=6%3A162

**Comment by gazpachu** [comment]
In figma the outline button border is using PURPLE.L5, which is our primary1

<img width="893" alt="Screen Shot 2021-11-25 at 11 44 12" src="https://user-images.githubusercontent.com/1721288/143370778-90a8df3b-301e-4b74-95ab-59518e5ef15b.png">

**Comment by SimeonC** [comment]
For the outline yes, the text is primary 2 though.

![CleanShot 2021-11-25 at 11 46 03](https://user-images.githubusercontent.com/1085899/143370945-e2f5c3f5-d25d-4bd4-96ce-990c20737445.png)

**Comment by gazpachu** [comment]
Not relevant anymore. Closing issue
