### ISSUE TITLE
Password component not respecting underscores as special characters

### ISSUE THREAD

**Issue by hachi-studio** [tablecheck/tablekit#78]
There may be more special characters not respected, but I think _ is a typical character appended to passwords to fulfill the requirement. 

As a user, I was confused why it was not working

https://user-images.githubusercontent.com/21358603/148334996-d85262d7-ca9f-4569-a2eb-d8516e82dbc9.mov

.

**Comment by gazpachu** [comment]
Some background of why `_` was not catched:

https://www.quora.com/Why-is-an-underscore-not-regarded-as-a-non-word-character-This-regexp-W-matches-all-non-word-character-but-not-the-underscore

Our current regex: 
```
if (!/(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*\W)/i.test(value)) {
    return I18nMessageFlag.InvalidFormat;
  }
```

**Comment by gazpachu** [comment]
Done
