### ISSUE TITLE
Input label should be react.node or string 

### ISSUE THREAD

**Issue by daniellizik** [tablecheck/tablekit#96]
## Problem

For the booking form, the shop enquete titles have to support dangerously set innerHTML, example:

<img width="767" alt="Screen Shot 2022-05-12 at 14 49 52" src="https://user-images.githubusercontent.com/10506366/168000943-46f77100-407c-476c-a320-60d3ac468b2c.png">

In pseudocode the booking form markup needs to look like

```
Wrapper
  TKInputLabel
    form q1 dis red // this needs to be set via dangerous innerHTML
  options.map
    TKCheckbox
      {checkbox text}
```

If I pass in a react node to `children`, however, the input label wrapper styling is lost (since children is not inside that specific wrapper)

<img width="737" alt="Screen Shot 2022-05-12 at 14 59 05" src="https://user-images.githubusercontent.com/10506366/168002194-7df364b9-f663-4d3b-b0aa-eb1053d849b2.png">

---

## Possible solutions

1. Export the label wrapper styles so that users can format `Label.children` to look like the actual label. No breaking changes.
2. Change the `Label.label` prop to be `React.ReactNode | string`. No breaking changes (?). But since the label inner child wrapper is `<span>` we might run into issues with trying to put block elements into the inline-block span.
3. Add some prop to indicate the inner label span wrapper should dangerously set html. With this, there won't be any potential semantic html problems but IMO tablekit shouldn't have to deal with innerHTML at all.

---

see:
- https://staging-qa.tablecheck.com/en/shops/daniel/reserve

**Comment by daniellizik** [comment]
As a super quick and dirty fix in the booking form I could simply use `children` and duplicate the label styles 🤷

**Comment by SimeonC** [comment]
I think option 2 is the best one for now. In TK3.0 the label component will become a simple styled component with no internal structure (at least that's what I have in my current local draft).
